### ISSUE TITLE
分页组件BUG

### ISSUE THREAD

**Issue by Xu-Angel** [Z6T/nature-ui#11]
![image](https://user-images.githubusercontent.com/25033729/62546248-b6eaf480-b895-11e9-90c7-eb64d2277bb2.png)

=>

![image](https://user-images.githubusercontent.com/25033729/62546183-9e7ada00-b895-11e9-953f-eb0abbbc7da0.png)

**Comment by Z6T** [comment]
> ![image](https://user-images.githubusercontent.com/25033729/62546248-b6eaf480-b895-11e9-90c7-eb64d2277bb2.png)
> 
> =>
> 
> ![image](https://user-images.githubusercontent.com/25033729/62546183-9e7ada00-b895-11e9-953f-eb0abbbc7da0.png)

谢谢您了.我改一下

**Comment by Z6T** [comment]
> ![image](https://user-images.githubusercontent.com/25033729/62546248-b6eaf480-b895-11e9-90c7-eb64d2277bb2.png)
> 
> =>
> 
> ![image](https://user-images.githubusercontent.com/25033729/62546183-9e7ada00-b895-11e9-953f-eb0abbbc7da0.png)

应该是你点了两次那个省略的按钮,我把省略按钮的方法禁用掉就行了

**Comment by Xu-Angel** [comment]
加油~
